### PR TITLE
fix: fix compile task, update publish workflow, include lib folder

### PR DESCRIPTION
**Pull request by fczbkk**
I have tried to use this library via NPM and it didn't work. The reason was missing `/lib` folder with compiled library. This pull request contains these changes:
- The `compile` task should now correctly build the library to the `/lib` folder. I have also included the compiled library, so it is ready to publish.
- The publish workflow should now be simpler. Just use `npm version [patch | minor | major]`. It will automatically bump the package version, build the library, create GIT tags, commit and publish to NPM.

If you accept this pull request, please consider doing the `npm version major` and publishing it as `v1.0.0`. I think there's no reason to cowardly hide behind `v0.0.x` anymore. The library works just fine.

Thank you.

### CODE REVIEW

**Comment by AndrewRayCode** [comment]
This library works fine for me on a fresh install:

```
andrewray@~ $ cd test

andrewray@~/test $ npm install easing-utils
/Users/andrewray/test
├── babel-cli@6.6.5
├── babel-preset-es2015@6.6.0
├── easing-utils@0.0.4
├── eslint@2.9.0
├── eslint-plugin-import@1.0.3
├── p2@0.7.1
├── physicsjs@0.7.0
├── shader-particle-engine@1.0.5
└── three@0.76.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/andrewray/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

andrewray@~/test $ node
> var a = require('easing-utils')
undefined

> a.easeInQuad(1)
1
```

I will investigate this PR further today. Just to double check, are you installing the package from NPM, and not from this github repo? Pointing directly to this repo probably won't work.

**Comment by DelvarWorld** [comment]
oh wow I should clean up package.json

**Comment by fczbkk** [comment]
Yes, I have tried to install it from NPM. Didn't work. The `/lib` folder is missing and the `package.json` links to that folder.

**Comment by AndrewRayCode** [comment]
That file shows up for me:

```
andrewray@~/test $ ls node_modules/easing-utils/lib/
easing.js
```

It's generated from the [prepublish step](https://github.com/DelvarWorld/easing-utils/blob/master/package.json#L9). It's a common pattern for npm modules as far as I know.

Can you show me your output of these commands?

```
mkdir test
cd test
npm install easing-utils
ls node_modules/easing-utils/lib/
```

Just trying to check my assumptions here. Also what is your npm version? `npm --version` is showing me `3.8.0`.

**Comment by fczbkk** [comment]
Strange. When I tried it now on an empty project. It worked. When I tried it before in an existing project, it failed. I have used `npm install easing-utils --save` command.

Andrew Ray wrote:

**Comment by AndrewRayCode** [comment]
Cool! Is it ok to close this PR?

I can't accept this PR because it contains compiled code, and compiled code shouldn't be committed to git repos. If there's still a bug though we can find a solution. But I'm not sure what would be causing it...

**Comment by fczbkk** [comment]
Sure.

**Comment by AndrewRayCode** [comment]
If you're still seeing `lib/` missing when you re-install it in your main project, can you show your npm version? Wondering if npm does something differently between 2/3, and it's possible if you're using nvm to manage multiple node versions that a fresh folder/install might have a different node+npm version.

**Comment by fczbkk** [comment]
```
~: npm -v
3.8.3
~: node -v
v5.10.1
```

**Comment by fczbkk** [comment]
@DelvarWorld Just one more thing. Can you please add `.babelrc` file to the `.npmignore`? It's causing this problem when used in project using Webpack and Babel:

```
ERROR in ./~/easing-utils/lib/easing.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/fczbkk/projects/js-libraries/animate/node_modules/easing-utils/.babelrc" at 0, attempted to resolve relative to "/Users/fczbkk/projects/js-libraries/animate/node_modules/easing-utils"
```

**Comment by fczbkk** [comment]
UPDATE: Just spend half a day trying to solve this. There's a bug in Babel, that ignores the `ignore` option anywhere but in CLI: https://phabricator.babeljs.io/T6726

**Comment by AndrewRayCode** [comment]
I added `.babelrc` to `.npmignore` either way. Released `easing-utils@0.0.5`. Still keeping the minor version for now because as far as I know you and I are the only people using this in the wild.

**Comment by fczbkk** [comment]
Thank you.

By the way, semver is not about the number of people who are using it.

**Pull request closed without merging**
